export const surpriseMePrompts = [
  "A serene beach at sunset with vibrant colors reflecting on the water.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A mystical forest filled with bioluminescent plants and magical creatures.",
  "A cozy cabin in the snowy mountains with smoke coming out of the chimney.",
  "An underwater world teeming with colorful coral reefs and exotic fish.",
  "A vast desert landscape with sand dunes stretching as far as the eye can see.",
  "A group of hot air balloons floating gracefully against a blue sky.",
  "A bustling marketplace with vendors selling vibrant fruits and vegetables.",
  "A dramatic thunderstorm with lightning illuminating a dark, stormy sky.",
  "A field of blooming sunflowers with a clear blue sky in the background.",
  "A winding mountain road surrounded by lush green forests.",
  "An ancient castle perched on a cliff overlooking a turbulent sea.",
  "A picturesque vineyard with rows of grapevines and a charming farmhouse.",
  "A vibrant carnival scene with Ferris wheel, merry-go-round, and colorful booths.",
  "A tranquil lake reflecting a picturesque mountain range.",
  "A whimsical garden with oversized flowers and talking animals.",
  "A starry night sky with the Milky Way galaxy stretching across it.",
  "A misty waterfall cascading down moss-covered rocks in a lush rainforest.",
  "A serene countryside with rolling hills and grazing farm animals.",
  "A surreal dreamscape with floating islands and whimsical creatures.",
  "A bustling city street at night, illuminated by neon signs and bustling with activity.",
  "A vast field of lavender in full bloom, swaying gently in the breeze.",
  "A cozy library filled with shelves of books and soft reading nooks.",
  "A charming cottage surrounded by colorful flower gardens.",
  "A tropical paradise with palm trees, crystal-clear water, and white sandy beaches.",
  "A vibrant street art mural covering the side of a building.",
  "A magical winter wonderland with snow-covered trees and a frozen lake.",
  "An ancient temple nestled in the midst of a lush jungle.",
  "A serene river winding through a dense forest, surrounded by wildlife.",
  "A whimsical tea party in a meadow, attended by talking animals.",
  "A surreal cityscape with upside-down buildings and floating islands.",
  "A bustling harbor filled with sailboats and seagulls.",
  "A peaceful zen garden with carefully raked sand and serene bonsai trees.",
  "A vibrant autumn forest with trees in shades of red, orange, and yellow.",
  "A traditional Japanese pagoda set against a backdrop of cherry blossom trees.",
  "An otherworldly alien landscape with strange rock formations and colorful skies.",
  "A serene farmstead with rolling green fields and grazing livestock.",
  "A hidden waterfall tucked away in a remote mountainous region.",
  "A charming European village with cobblestone streets and colorful buildings.",
  "A spooky haunted mansion shrouded in mist and surrounded by overgrown vegetation.",
  "A bustling street market with vendors selling a variety of exotic goods.",
  "A futuristic space station orbiting a distant planet.",
  "A vast savannah with a herd of majestic elephants crossing the plains.",
  "A cozy campfire scene with friends gathered around, roasting marshmallows.",
  "A serene sunrise over a calm lake, painting the sky in hues of pink and orange.",
  "A whimsical underwater scene."
  ];